like_publication:
    path: /like/{id}
    defaults: { _controller: AppBundle:Like:like, id: null }

unlike_publication:
    path: /unlike/{id}
    defaults: { _controller: AppBundle:Like:unlike, id: null }

user_publications_like:
    path: /publications-like/{nickname}
    defaults: { _controller: AppBundle:Like:publicationLikes, nickname: null }