home_publication:
    path: /home
    defaults: { _controller: AppBundle:Publication:index }

remove_publication:
    path: /publication/delete/{id}
    defaults: { _controller: AppBundle:Publication:removePublication, id: null }