login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

user_nickname:
    path: /nickname-check
    defaults: { _controller: AppBundle:User:nicknameCheck }
    methods: [POST]