login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

login_check:
    path: /login-check

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

user_nickname:
    path: /nickname-check
    defaults: { _controller: AppBundle:User:nicknameCheck }
    methods: [POST]

profile-settings:
    path: /profile-settings
    defaults: { _controller: AppBundle:User:editUser}