<?php

namespace BackendBundle\Repository;

/**
 * FollowingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowingRepository extends \Doctrine\ORM\EntityRepository
{
}
