BackendBundle\Entity\User:
    type: entity
    table: users
    uniqueConstraints:
        users_uniques_fields:
            columns:
                - email
                - nickname
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        firstname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: lastName
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nickname:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        biografy:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        active:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
